#!/usr/bin/env python3
"""Generate the memory images consumed by the Logisim datapath."""

import argparse
from pathlib import Path


CONTROL_WORDS = {
    0x00: 0x1A1,  # R-format
    0x04: 0x1C0,  # BEQ
    0x05: 0x3C0,  # BNE
    0x08: 0x091,  # ADDI
    0x23: 0x09B,  # LW
    0x2B: 0x194,  # SW
}

ALU_FUNCTIONS = {
    0x20: 0x0,  # ADD
    0x22: 0x1,  # SUB
    0x24: 0x2,  # AND
    0x25: 0x3,  # OR
    0x2A: 0x4,  # SLT
}


def write_raw(path, values, width):
    with path.open("w", encoding="ascii") as output:
        output.write("v2.0 raw\n")
        for offset in range(0, len(values), 8):
            output.write(" ".join(f"{value:0{width}x}" for value in values[offset:offset + 8]))
            output.write("\n")


def read_program_words(path):
    tokens = path.read_text(encoding="ascii").split()
    if not tokens or tokens[0] != "v2.0":
        raise ValueError(f"{path} is not a Logisim v2.0 raw image")
    return [int(token, 16) for token in tokens[2:]]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--program", type=Path, required=True,
                        help="seeded .hex program generated by gen_cocobod_instrs.py")
    parser.add_argument("--outdir", type=Path, default=Path("hardware/images"))
    args = parser.parse_args()

    args.outdir.mkdir(parents=True, exist_ok=True)
    program_words = read_program_words(args.program)
    write_raw(args.outdir / "imem.hex", program_words, 8)
    write_raw(args.outdir / "control_rom.hex",
              [CONTROL_WORDS.get(opcode, 0) for opcode in range(64)], 3)
    write_raw(args.outdir / "alu_rom.hex",
              [ALU_FUNCTIONS.get(funct, 0) for funct in range(64)], 1)
    write_raw(args.outdir / "dmem_init.hex",
              [(37 * index + 11) % 1000 for index in range(256)], 8)

    print(f"wrote {args.outdir / 'imem.hex'} ({len(program_words)} words)")
    print(f"wrote {args.outdir / 'control_rom.hex'} (64 entries)")
    print(f"wrote {args.outdir / 'alu_rom.hex'} (64 entries)")
    print(f"wrote {args.outdir / 'dmem_init.hex'} (256 words)")


if __name__ == "__main__":
    main()